"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['amonitor.py']
DATA_FILES = ['./app']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'res/icon.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
